spring:
  profiles:
    active: native

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
