server:
  port: 9001

spring:
  application:
    name: ms-classe

  data:
    mongodb:
      host: localhost
      port: 27017
      database: classe-db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
