server:
  port: 9002

spring:
  application:
    name: ms-etudiant

  graphql:
    path: /graphql         # Important !
    graphiql:
      enabled: true
      path: /graphiql

  data:
    mongodb:
      host: localhost
      port: 27017
      database: etudiant-db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
