server:
  port: 9002

spring:
  application:
    name: ms-etudiant

  graphql:
    path: /graphql         # Permet d'accéder à /graphql via POST
    graphiql:
      enabled: true
      path: /graphiql      # Accès interactif : http://localhost:9002/graphiql

  data:
    mongodb:
      host: localhost
      port: 27017
      database: etudiant-db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
