# server:
#   port: 8080

# spring:
#   application:
#     name: ms-gateway
#   cloud:
#     gateway:
#       routes:
#         - id: ms-etudiant
#           uri: lb://ms-etudiant
#           predicates:
#             - Path=/api/etudiant/**
#           filters:
#             - StripPrefix=1  # Enlève '/api' de l'URL avant routage
#         - id: ms-classe
#           uri: lb://ms-classe
#           predicates:
#             - Path=/api/classe/**
#           filters:
#             - StripPrefix=1
#       httpclient:
#         connect-timeout: 1000  # Timeout en ms
#         response-timeout: 5s   # Timeout des réponses

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
#     healthcheck:
#       enabled: true  # Active les checks de santé pour Eureka

# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG  # Logs détaillés pour le routage


server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-etudiant
              uri: lb://ms-etudiant
              predicates:
                - Path=/api/etudiant/**
              filters:
                - StripPrefix=1  # Enlève '/api' avant routage
            - id: ms-classe
              uri: lb://ms-classe
              predicates:
                - Path=/api/classe/**
              filters:
                - StripPrefix=1
          httpclient:
            connect-timeout: 1000     # Timeout en ms
            response-timeout: 5s      # Timeout des réponses
          discovery:
            locator:
              enabled: false          # True si tu veux activer le routage auto par Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
