server:
  port: 8080

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-etudiant
              uri: lb://ms-etudiant
              predicates:
                - Path=/api/etudiant/**
              filters:
                - StripPrefix=2

            - id: ms-classe
              uri: lb://ms-classe
              predicates:
                - Path=/api/classe/**
              filters:
                - StripPrefix=2

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

      discovery:
        locator:
          enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
